apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ff2r5i2n8-python 
  janus-idp.io/tekton: ff2r5i2n8-python
  backstage.io/kubernetes-id: ff2r5i2n8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ff2r5i2n8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml