apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ff2r5i2n8-python
  janus-idp.io/tekton: ff2r5i2n8-python
  backstage.io/kubernetes-id: ff2r5i2n8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ff2r5i2n8-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
